baseURL = "https://etheriamagazine-com.fly.dev/"
title = "Etheria Magazine"
defaultContentLanguage = "es"
enableGitInfo = true
removePathAccents = true
summaryLength = 20

[build]
  # this is necessary in production so that hugo_stats.json is picked by tailwindcss
  [build.buildStats]
    enable = true

[frontmatter]
  lastmod = ['lastmod', 'modified', 'date', 'publishDate', 'pubdate']

[outputs]
  home = ["html"]

[taxonomies]
  category = "categories"
  author = "authors"
  destino = "destino"

[pagination]
  disableAliases = false
  pagerSize = 20
  path = "page"

[permalinks]
  [permalinks.page]
    posts = "/articulos/:filename"

  [permalinks.taxonomy]
    categories = "/categorias"
    authors = "/autoras"

  [permalinks.term]
    categories = "/:slug"
    authors = "/autoras/:slug"


[markup]
  _merge = "deep"

[minify]
  minifyOutput = true

[related]
  includeNewer = true
  threshold = 80
  toLower = true

  [[related.indices]]
    name = 'authors'
    weight = 2
  [[related.indices]]
    name = 'categories'
    weight = 1


[module]
  [[module.imports]]
    path = "github.com/etheriamagazine/hugo-modules/sky-theme"
