# Hugo site configuration
baseURL = 'https://etheriamagazine.com/'
title = 'Etheria Magazine'
# languageCode = 'es-ES'
defaultContentLanguage = 'es'

removePathAccents = true
# summary length in words is approximate as hugo cuts always
# on a sentence
summaryLength = 20

[outputs]
  home = ["html", "json"]
[taxonomies]
  category = 'categories'
  author = 'authors'

[permalinks]
  [permalinks.page]
    posts = '/:year/:month/:day/:filename'

  [permalinks.section]
    posts = '/articulos'

  [permalinks.taxonomy]
    categories = "/categorias"
    authors = "/autores"

  [permalinks.term]
    categories = "/categorias/:slug/"
    authors = "/autores/:slug"


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github-ascii"
      wrapStandAloneImageWithinParagraph = false

# import hugo-etheria module which implements all the sites templates
[module]
  [[module.imports]]
    path = 'github.com/etheriamagazine/hugo-etheria'



[params]
  subtitle = "1ª revista de viajes española para mujeres que les apasiona viajar"

  [params.publisher]
    name = 'Etheria Magazine'
    urls = [
      "https://www.facebook.com/etheriamagazine/",
      "https://twitter.com/etheriamagazine",
      "https://www.instagram.com/etheriamagazine/",
      "https://www.pinterest.es/etheriamagazine/",
      "https://github.com/etheriamagazine"      
    ]

  [params.publi]
    items = [
      "publi/2023-polonia",
      "publi/2024-biofest",
      "publi/2022-getxo"
    ]

  [params.imgproxy]
    enabled = true
    host = "https://imgp.etheriamagazine.com/"
    sourceStyle = "plain"
    responsiveSizes = [200, 300, 600, 900, 1200] 
    defaultSize = 600

  [params.hugoEtheria]
    [params.hugoEtheria.subscribeForm]
      action = "/newsletter"  
  

  [params.subscribe]
    action = "/newsletter"
    [[params.subscribe.lists]]
      id = "3yExM8x4"
      label = "Newsletter"


    [[params.subscribe.lists]]
      id = "3yExM8x4"
      label = "Marketing"      