[build]
  [build.buildStats]
    enable = true

  [[build.cachebusters]]
    source = "layouts/.*"
    target = "css"

  [[build.cachebusters]]
    source = "assets/js/.*"
    target = "css"

  [[build.cachebusters]]
      source = "assets/notwatching/hugo_stats\\.json"
      target = "css"

[module]
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
      source  = "hugo_stats.json"
      target = "assets/notwatching/hugo_stats.json"
      disableWatch = true
