build:
  buildStats:
    enable: true
  cachebusters:
    - source: layouts/.*
      target: css
    - source: assets/js/.*
      target: css
    - source: assets/notwatching/hugo_stats\.json
      target: css

module:
  mounts:
    - source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json
      disableWatch: true
