[build]

  [[build.cachebusters]]
    source = "layouts/.*"
    target = "css"

  [[build.cachebusters]]
    source = "assets/js/.*"
    target = "css"

  [[build.cachebusters]]
      source = "assets/notwatching/hugo_stats\\.json"
      target = "css"

[module]

  [[module.mounts]]
      source  = "hugo_stats.json"
      target = "assets/notwatching/hugo_stats.json"
      disableWatch = true
