# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main    # change to main if needed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # see https://gohugo.io/methods/page/gitinfo/#hosting-considerations

      - uses: superfly/flyctl-actions/setup-flyctl@master

      # NOTE: IMGPROXY secrets are set in github and used as part of the build process, not at runtime
      - run: flyctl deploy --remote-only --build-secret HUGO_IMGPROXY_KEY="${{ secrets.HUGO_IMGPROXY_KEY }}" --build-secret HUGO_IMGPROXY_SALT="${{ secrets.HUGO_IMGPROXY_SALT }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
