name: Test Hugo Build
on:
  pull_request:
    types: [ opened, edited, reopened, review_requested ]
    branches:
      - main

  workflow_dispatch:

jobs:
  build-hugo:
    name: Build Hugo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # see https://gohugo.io/methods/page/gitinfo/#hosting-considerations

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

